### ISSUE TITLE
Cannot save OGG files

### ISSUE THREAD

**Issue by foo-dogsquared** [knuxify/eartag#23]
Self-explanatory title is self-explanatory.

Here's the steps how to reproduce it:

- Open an OGG file. 
- Fill up values in the application. It shouldn't matter but edit the release year just to be safe since it seems to be where the error came from glancing at the traceback (which is attached later in this issue).
- Save the file.

---

What is expected? Should save the file successfully.
What happened? An error popped up.

![image](https://user-images.githubusercontent.com/34962634/189484403-182fe933-2160-48f3-8f3e-03b49c0f76ec.png)

This is installed with Flatpak, version 0.2.0.

Running it in the command line to see the output, it printed the following traceback:

```
Traceback (most recent call last):
  File "/app/share/eartag/eartag/file.py", line 163, in save
    file.save()
  File "/app/share/eartag/eartag/backends/file_mutagen_vorbis.py", line 74, in save
    self.mg_file.save()
  File "/app/lib/python3.9/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/mutagen/ogg.py", line 587, in save
    self.tags._inject(filething.fileobj, padding)
  File "/app/lib/python3.9/site-packages/mutagen/oggvorbis.py", line 137, in _inject
    vcomment_data = b"\x03vorbis" + self.write()
  File "/app/lib/python3.9/site-packages/mutagen/_vorbis.py", line 178, in write
    self.validate()
  File "/app/lib/python3.9/site-packages/mutagen/_vorbis.py", line 158, in validate
    raise ValueError(err)
ValueError: 1995 needs to be str for key 'date'
```

I also built and tested the application with Nix and it gave the same error.

**Comment by foo-dogsquared** [comment]
That was quick. I can confirm it's been fixed. Thank you! (And doubly thanks for creating this app. It goes nicely with Amberol, too.)
